#ifndef PERSIST_H
#define PERSIST_H
#include <stdio.h>

//Saves all the weights, biases and activations of all the layer's neurons into a text file
void SaveNeural();

//Loads all the weights, biases and activations of all the layer's neurons from a path leading to a text file
void LoadNeuralPath(char* fileName);

//Sets the values of all weights, biases and activation 
//from a file in the format generated by SaveNeural
void LoadNeural();

#endif